
<?php echo $this->getContent() ?>

<ol class="breadcrumb">
    <li><?php echo $this->tag->linkTo(array("acos/new", "Create acos")) ?></li>
</ol>

<?php echo $this->tag->form(array("acos/search", "autocomplete" => "off")) ?>

    <h1>Search acos</h1>
    <div class="form-group">
        <label for="id">Id</label>
        <?php echo $this->tag->textField(array("id", "type" => "number", "class" => "form-control")) ?>
    </div>
    <div class="form-group">
        <label for="controller">Controller</label>
        <?php echo $this->tag->textField(array("controller", "size" => 30, "class" => "form-control")) ?>
    </div>
    <div class="form-group">
        <label for="action">Action</label>
        <?php echo $this->tag->textField(array("action", "size" => 30, "class" => "form-control")) ?>
    </div>
    <div class="form-group">
        <label for="hide">Hide</label>
        <?php echo $this->tag->textField(array("hide", "size" => 30, "class" => "form-control")) ?>
    </div>

    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group">
            <button type="submit" class="btn btn-default">Search</button>
        </div>
    </div>
</form>
