<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<ol class="breadcrumb">
    <li><?php echo $this->tag->linkTo(array("groups", "Back")) ?></li>
    <li><?php echo $this->tag->linkTo(array("groups/new", "Create ")); ?></li>
</ol>

<h1>groups</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Note</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $group) { ?>
        <tr>
            <td><?php echo $group->getId() ?></td>
            <td><?php echo $group->getName() ?></td>
            <td><?php echo $group->getNote() ?></td>
            <td><?php echo $this->tag->linkTo(array("groups/edit/" . $group->getId(), "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("groups/delete/" . $group->getId(), "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>

<ul class="pager">
    <li><?php echo $this->tag->linkTo("groups/search", "First") ?></li>
    <li><?php echo $this->tag->linkTo("groups/search?page=" . $page->before, "Previous") ?></li>
    <li><?php echo $this->tag->linkTo("groups/search?page=" . $page->next, "Next") ?></li>
    <li><?php echo $this->tag->linkTo("groups/search?page=" . $page->last, "Last") ?></li>
    <li><?php echo $page->current, "/", $page->total_pages ?></li>
</ul>

