
<?php echo $this->getContent() ?>

<ol class="breadcrumb">
    <li><?php echo $this->tag->linkTo(array("users/new", "Create users")) ?></li>
</ol>

<?php echo $this->tag->form(array("users/search", "autocomplete" => "off")) ?>

    <h1>Search users</h1>
    <div class="form-group">
        <label for="id">Id</label>
        <?php echo $this->tag->textField(array("id", "type" => "number", "class" => "form-control")) ?>
    </div>
    <div class="form-group">
        <label for="username">Username</label>
        <?php echo $this->tag->textField(array("username", "size" => 30, "class" => "form-control")) ?>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <?php echo $this->tag->textField(array("password", "size" => 30, "class" => "form-control")) ?>
    </div>

    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group">
            <button type="submit" class="btn btn-default">Search</button>
        </div>
    </div>
</form>
